CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12324 \
downstream_phase/run_phase_training.py \
--batch_size 2 \
--epochs 50 \
--save_ckpt_freq 5 \
--model  surgformer_HTA \
--pretrained_path pretrain_params/timesformer_base_patch16_224_K400.pyth \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path /home/han/Documents/github/halo_project/dataset/dataset_keyframe/ \
--eval_data_path /home/han/Documents/github/halo_project/dataset/dataset_keyframe/ \
--nb_classes 11 \
--data_strategy offline \
--output_mode all_frame \
--num_frames 16 \
--sampling_rate 1 \
--data_set halo \
--data_fps 1fps \
--output_dir /mnt/hdd1/ale/Surgformer/outputs/halo_depth_relaxed \
--log_dir /mnt/hdd1/ale/Surgformer/outputs/halo_depth_relaxed \
--num_workers 10
